### ISSUE TITLE
@RequestMapping  不注解在类上，返回值的格式为xml 

### ISSUE THREAD

**Issue by yhc19850706** [xujijun/spring-boot-101#4]
`@RestController
public class AdminController {

	//@Value("${spring.profiles}")
	//private String env;
	
	private String userName = "admin";
	private String pw = "pword";
	
	/**
	 * 登录
	 * @param response：用于保存token到cookie中
	 * @param map：包含userName和password
	 * @return
	 */
	@RequestMapping("/login")
	public JsonResult login(HttpServletRequest request, HttpServletResponse response, @RequestParam Map<String, String> map) {
		if(userName.equals(map.get("userName")) && pw.equals(map.get("password"))){
			return new JsonResult(ResultCode.SUCCESS, "登录成功！", null);
		}else {
			return new JsonResult(ResultCode.NOT_LOGIN, "登录失败！", null);
		}
	}
}`
此时访问 http://localhost:8080/login?userName=admin&password=pword 返回的是 xml 格式
《JsonResult》
《code》 200 《code》
《message》登录成功！《message》
《data》
《JsonResult》

如果在类名上面这么些
`@RestController
@RequestMapping("/api/admin")
public class AdminController`
返回值的格式为json字符串 {"code":"200","message":"登录成功！","data":null}

请问这个是为什么？

**Comment by xujijun** [comment]
是不是你把类上面的`@RestController这个注释掉了？
